/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorldsRouteImport } from './routes/worlds'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ManifestoRouteImport } from './routes/manifesto'
import { Route as LookbookRouteImport } from './routes/lookbook'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShopIndexRouteImport } from './routes/shop.index'
import { Route as ShopIdRouteImport } from './routes/shop.$id'

const WorldsRoute = WorldsRouteImport.update({
  id: '/worlds',
  path: '/worlds',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ManifestoRoute = ManifestoRouteImport.update({
  id: '/manifesto',
  path: '/manifesto',
  getParentRoute: () => rootRouteImport,
} as any)
const LookbookRoute = LookbookRouteImport.update({
  id: '/lookbook',
  path: '/lookbook',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopIndexRoute = ShopIndexRouteImport.update({
  id: '/shop/',
  path: '/shop/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopIdRoute = ShopIdRouteImport.update({
  id: '/shop/$id',
  path: '/shop/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/checkout': typeof CheckoutRoute
  '/lookbook': typeof LookbookRoute
  '/manifesto': typeof ManifestoRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/worlds': typeof WorldsRoute
  '/shop/$id': typeof ShopIdRoute
  '/shop/': typeof ShopIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/checkout': typeof CheckoutRoute
  '/lookbook': typeof LookbookRoute
  '/manifesto': typeof ManifestoRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/worlds': typeof WorldsRoute
  '/shop/$id': typeof ShopIdRoute
  '/shop': typeof ShopIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/checkout': typeof CheckoutRoute
  '/lookbook': typeof LookbookRoute
  '/manifesto': typeof ManifestoRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/worlds': typeof WorldsRoute
  '/shop/$id': typeof ShopIdRoute
  '/shop/': typeof ShopIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/checkout'
    | '/lookbook'
    | '/manifesto'
    | '/sitemap.xml'
    | '/worlds'
    | '/shop/$id'
    | '/shop/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/checkout'
    | '/lookbook'
    | '/manifesto'
    | '/sitemap.xml'
    | '/worlds'
    | '/shop/$id'
    | '/shop'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/checkout'
    | '/lookbook'
    | '/manifesto'
    | '/sitemap.xml'
    | '/worlds'
    | '/shop/$id'
    | '/shop/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  CheckoutRoute: typeof CheckoutRoute
  LookbookRoute: typeof LookbookRoute
  ManifestoRoute: typeof ManifestoRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  WorldsRoute: typeof WorldsRoute
  ShopIdRoute: typeof ShopIdRoute
  ShopIndexRoute: typeof ShopIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/worlds': {
      id: '/worlds'
      path: '/worlds'
      fullPath: '/worlds'
      preLoaderRoute: typeof WorldsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manifesto': {
      id: '/manifesto'
      path: '/manifesto'
      fullPath: '/manifesto'
      preLoaderRoute: typeof ManifestoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lookbook': {
      id: '/lookbook'
      path: '/lookbook'
      fullPath: '/lookbook'
      preLoaderRoute: typeof LookbookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/': {
      id: '/shop/'
      path: '/shop'
      fullPath: '/shop/'
      preLoaderRoute: typeof ShopIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/$id': {
      id: '/shop/$id'
      path: '/shop/$id'
      fullPath: '/shop/$id'
      preLoaderRoute: typeof ShopIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  CheckoutRoute: CheckoutRoute,
  LookbookRoute: LookbookRoute,
  ManifestoRoute: ManifestoRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  WorldsRoute: WorldsRoute,
  ShopIdRoute: ShopIdRoute,
  ShopIndexRoute: ShopIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
